# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================
spring:
    application:
        name: antiplagiarismfilecheckerservice
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
file:
    uploadDir: uploads

server:
    servlet:
        session:
            cookie:
                http-only: true


kafka:
    topic: antiplagiarism
    bootstrapAddress: 192.168.0.26:9092,192.168.0.26:9093,192.168.0.26:9094
