
logging:
    level:
        ROOT: DEBUG
        com.antiplagiarism.fileuploadservice: DEBUG


spring:
    profiles:
        active: dev

    devtools:
        restart:
            enabled: true
            additional-exclude: .h2.server.properties
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization:
            indent-output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/flatterservermonolith;DB_CLOSE_DELAY=-1
        username: sa
        password:
        hikari:
            poolName: Hikari
            auto-commit: false
    h2:
        console:
            enabled: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
