# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================
spring:
    application:
        name: antiplagiarismuploadservice
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC

        hibernate:
            ddl-auto: create-drop
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        generate-ddl: true
    kafka:
        max:
            message:
                bytes: 7000000

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            location: /etc/uploads/upload_tmp
file:
    uploadDir: uploads

server:
    servlet:
        session:
            cookie:
                http-only: true


kafka:
    topic: fileadded
    bootstrapAddress: 192.168.0.26:9092,192.168.0.26:9093,192.168.0.26:9094


eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone:  http://localhost:8761/eureka
    instance:
        preferIpAddress: true
