spring:
    application:
        name: antiplagiarismuploadservice
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC

        hibernate:
            ddl-auto: create-drop
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        generate-ddl: true
    kafka:
        max:
            message:
                bytes: 7000000

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            location: /etc/uploads/upload_tmp
file:
    uploadDir: uploads

server:
    servlet:
        session:
            cookie:
                http-only: true


kafka:
    topic: fileadded
    bootstrapAddress: 192.168.0.26:9092,192.168.0.26:9093,192.168.0.26:9094


# configure eureka client
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 3
    client:
        serviceUrl:
            defaultZone: http://admin:admin@localhost:8761/eureka/




